spring:
  application:
    name: notas
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-noisy-wind-auvjlq6g-pooler.c-10.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_ewKR8QPNCD4Y}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: ${JWT_SECRET:UnSecretoMuyLargoParaElJWTDeKomodoNotasAppQueDebeSerMayorA256BitsParaSerSeguro}
    expiration-ms: ${JWT_EXPIRATION_MS:1576800000000} # 50 años
  resend:
    api-key: ${RESEND_API_KEY:re_VNzZtd3i_8DLwFpsMESwbT1T8L3jBhtnc}
    from-email: ${RESEND_FROM_EMAIL:onboarding@resend.dev}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200}

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    com.komodo.notas.controller: DEBUG
    com.komodo.notas.service: DEBUG
